import {MD3LightTheme, MD3DarkTheme} from 'react-native-paper';

const sharedColors = {
  accent: '#FFC107',
  error: '#D32F2F',
  notification: '#FF5252',
  info: '#2196F3',
  success: '#4CAF50',
  warning: '#FF9800',
};

export const GramSevaLightTheme = {
  ...MD3LightTheme,
  roundness: 12,
  colors: {
    ...MD3LightTheme.colors,
    primary: '#007BFF',
    onPrimary: '#FFFFFF',
    primaryContainer: '#E3F2FD',
    onPrimaryContainer: '#004085',
    secondary: '#00695C',
    onSecondary: '#FFFFFF',
    secondaryContainer: '#B2DFDB',
    onSecondaryContainer: '#003D33',
    tertiary: '#6A1B9A',
    onTertiary: '#FFFFFF',
    tertiaryContainer: '#E1BEE7',
    onTertiaryContainer: '#38006b',
    background: '#F8F9FA',
    onBackground: '#121212',
    surface: '#FFFFFF',
    onSurface: '#121212',
    surfaceVariant: '#E9ECEF',
    onSurfaceVariant: '#495057',
    outline: '#ADB5BD',
    ...sharedColors,
  },
};

export const GramSevaDarkTheme = {
  ...MD3DarkTheme,
  roundness: 12,
  colors: {
    ...MD3DarkTheme.colors,
    primary: '#64B5F6',
    onPrimary: '#003366',
    primaryContainer: '#004c8c',
    onPrimaryContainer: '#E3F2FD',
    secondary: '#4DB6AC',
    onSecondary: '#003D33',
    secondaryContainer: '#004D40',
    onSecondaryContainer: '#B2DFDB',
    tertiary: '#CE93D8',
    onTertiary: '#38006b',
    tertiaryContainer: '#4a148c',
    onTertiaryContainer: '#E1BEE7',
    background: '#121212',
    onBackground: '#E9ECEF',
    surface: '#1E1E1E',
    onSurface: '#E9ECEF',
    surfaceVariant: '#343A40',
    onSurfaceVariant: '#ADB5BD',
    outline: '#6C757D',
    ...sharedColors,
  },
};
